import { library } from '@fortawesome/fontawesome-svg-core';
import { faBars, faMagnifyingGlass, faCartShopping, faTimes } from '@fortawesome/free-solid-svg-icons';

library.add(faBars, faMagnifyingGlass, faCartShopping, faTimes);
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yom! Food Delivery App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
